version: '3'

services:
  db:
    env_file:
      - ./dev.env
    image: postgres
  web:
    build: .
    env_file:
      - ./dev.env
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - db