version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app/:/app
    ports:
      - "8080:8080"
    env_file:
      - ./dev.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dev.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: